apiVersion: v1
kind: Service
metadata:
  name: keycloak-svc
  # labels:
  #   app: keycloak
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  type: NodePort
  # clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: quay.io/keycloak/keycloak:20.0.2
          # args: ['start', '--cache-stack=kubernetes']
          args: ['start-dev', '--health-enabled=true', '--proxy=edge']
          volumeMounts:
            - name: certs
              mountPath: '/etc/certs'
              readOnly: true
          env:
            - name: KEYCLOAK_ADMIN
              value: 'admin'
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: 'admin'
            # - name: KC_HTTPS_CERTIFICATE_FILE
            #   value: '/etc/certs/tls.crt'
            # - name: KC_HTTPS_CERTIFICATE_KEY_FILE
            #   value: '/etc/certs/tls.key'
            - name: KC_HEALTH_ENABLED
              value: 'true'
            - name: KC_METRICS_ENABLED
              value: 'true'
            - name: KC_HOSTNAME
              value: auth.findyourjob.tech
            - name: KC_PROXY
              value: 'edge'
            - name: KC_DB
              value: postgres
            - name: KC_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: findyourjob-secrets
                  key: password
            - name: KC_DB_URL_HOST
              value: findyourjob-postgresql-primary.default.svc.cluster.local
            - name: KC_DB_URL_DATABASE
              value: keycloak
            - name: KC_DB_URL_PORT
              value: '5432'
            # - name: KC_DB_URL
            #   value: 'jdbc:postgresql://postgres:$(KC_DB_PASSWORD)@findyourjob-postgresql-primary.default.svc.cluster.local:5432/keycloak'
            - name: KC_DB_USERNAME
              value: 'postgres'
            - name: jgroups.dns.query
              value: keycloak
          ports:
            - name: jgroups
              containerPort: 7600
            - name: https
              containerPort: 8443
            - name: http
              containerPort: 8080
          readinessProbe:
            # httpGet:
            #   scheme: HTTPS
            #   path: /health/ready
            #   port: 8443
            # initialDelaySeconds: 60
            # periodSeconds: 1
            httpGet:
              path: /realms/master
              port: 8080
      volumes:
        - name: certs
          secret:
            secretName: auth-tls-secret
