version: '3.7'

services:
  findyourjob-frontend:
    container_name: findyourjob-frontend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    env_file:
      - .env
