apiVersion: apps/v1
kind: Deployment
metadata:
  name: findyourjob-api
spec:
  strategy:
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  minReadySeconds: 5
  selector:
    matchLabels:
      app: findyourjob-api
  template:
    metadata:
      labels:
        app: findyourjob-api
    spec:
      imagePullSecrets:
        - name: docker-config-json
      containers:
        - name: findyourjob-api
          image: ghcr.io/nguyenphucbao68/findyourjob-api:latest
          # image: findyourjob-api:latest
          command:
            - /bin/sh
            - -c
            - yarn migrate:db --accept-data-loss && dumb-init node dist/server.js
          env:
            - name: API_PORT
              value: '4000'
            - name: LOGGER_ROUTE_NAME
              value: 'findyourjob'
            - name: LOGGER_ROUTE_STORAGE
              value: 'true'
            - name: NODE_ENV
              value: production
            - name: ENABLE_DEBUG_QUERY
              value: 'false'
            - name: ENABLE_CORS
              value: 'false'
            - name: SERVER_WHITE_LIST
              value: ''
            - name: APOLLO_PLAYGROUND
              value: 'false'
            - name: APOLLO_INTROSPECTION
              value: 'false'
            - name: APOLLO_DEBUG
              value: 'false'
            - name: APOLLO_TRACING
              value: 'false'
            - name: KEY_AUTHORIZATION
              valueFrom:
                secretKeyRef:
                  name: findyourjob-secrets
                  key: KEY_AUTHORIZATION
            - name: KEY_CONSOLE
              valueFrom:
                secretKeyRef:
                  name: findyourjob-secrets
                  key: KEY_CONSOLE
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: findyourjob-secrets
                  key: postgres-password
            - name: DATABASE_URL
              value: postgresql://postgres:$(POSTGRESQL_PASSWORD)@findyourjob-postgresql-primary.default.svc.cluster.local:5432/capstone
            - name: KEYCLOAK_PUBLIC_KEY
              valueFrom:
                secretKeyRef:
                  name: findyourjob-secrets
                  key: KEYCLOAK_PUBLIC_KEY
            - name: KEYCLOAK_REALM_NAME
              valueFrom:
                secretKeyRef:
                  name: findyourjob-secrets
                  key: KEYCLOAK_REALM_NAME
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: findyourjob-secrets
                  key: KEYCLOAK_CLIENT_ID
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: findyourjob-secrets
                  key: KEYCLOAK_CLIENT_SECRET
            - name: KEYCLOAK_BASE_URL
              value: http://keycloak.default.svc.cluster.local:8080/auth
              # valueFrom:
              #   configMapKeyRef:
              #     name: findyourjob-configmap
              #     key: keycloak-uri
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: findyourjob-secrets
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: findyourjob-secrets
                  key: AWS_SECRET_ACCESS_KEY
            - name: AWS_S3_REGION
              valueFrom:
                secretKeyRef:
                  name: findyourjob-secrets
                  key: AWS_S3_REGION
            - name: AWS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: findyourjob-secrets
                  key: AWS_BUCKET_NAME
            - name: CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: findyourjob-secrets
                  key: CLIENT_ID
            - name: CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: findyourjob-secrets
                  key: CLIENT_SECRET
            - name: GOOGLE_MAILER_REFRESH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: findyourjob-secrets
                  key: GOOGLE_MAILER_REFRESH_TOKEN
            - name: ADMIN_EMAIL_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: findyourjob-secrets
                  key: ADMIN_EMAIL_ADDRESS
            - name: HOST_IP
              value: localhost
            - name: KAFKA_CLIENT_ID
              value: capstone-producer
            - name: KAFKA_TOPIC_JOB
              value: job
            - name: KAFKA_TOPIC_COMPANY
              value: company
            - name: ELASTIC_BASEURL
              value: http://quickstart-es-http.default.svc.cluster.local:9200
            - name: ELASTIC_JOB_INDEX
              value: job
            - name: ELASTIC_COMPANY_INDEX
              value: company
            - name: ELASTIC_USERNAME
              value: elastic
            - name: ELASTIC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: quickstart-es-elastic-user
                  key: elastic
          imagePullPolicy: Always
          # imagePullPolicy: Never
          resources:
            # requests:
            #   cpu: '500m'
            #   memory: '1024Mi'
            # limits:
            #   cpu: '1000m'
            #   memory: '2048Mi'
            requests:
              cpu: '100m'
              memory: '528Mi'
            limits:
              cpu: '300m'
              memory: '528Mi'
          ports:
            - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: findyourjob-api-svc
spec:
  type: NodePort
  selector:
    app: findyourjob-api
  ports:
    - port: 4000
      targetPort: 4000
      # nodePort: 30001

---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: findyourjob-api-hpa
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: findyourjob-api
  targetCPUUtilizationPercentage: 80
