image:
  registry: docker.io
  repository: bitnami/postgresql
  tag: 16.2.0-debian-12-r6

architecture: replication

primary:
  service:
    type: NodePort
    nodePorts:
      postgresql: 30075

auth:
  enablePostgresUser: true
  ## @param auth.postgresPassword Password for the "postgres" admin user
  ##
  postgresPassword: '123456'
  ## @param auth.username Name for a custom user to create
  ##
  username: 'authuser'
  password: '123456'
  database: 'keycloak'
  replicationUsername: repl_user
  replicationPassword: '123456'
